# Generated by Django 3.2.5 on 2021-08-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='question_category',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='question_detail',
        ),
    ]
