# Generated by Django 3.2.5 on 2021-08-03 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFile',
            fields=[
                ('file_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('file', models.FileField(upload_to='files/')),
                ('payed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'sharedfiles',
            },
        ),
    ]
