# Generated by Django 3.2.5 on 2021-08-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='payed',
            new_name='paid',
        ),
    ]
